### ISSUE TITLE
Spanner: Force index use for BSO modified query

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/server-syncstorage#107]
In Spanner, secondary indexes are only utilized if the requested columns are found in the index keys per:
https://cloud.google.com/spanner/docs/secondary-indexes#index_directive

The BSO modified query in MySQL ends up using the [BsoLastModified](https://github.com/mozilla-services/server-syncstorage/blob/master/syncstorage/storage/sql/queries_spanner.py#L22) automatically, while Spanner ignores the index since the query requests columns not in the index. The modified query (to find BSO items newer than modified) should be updated with the FORCE_INDEX directive to ensure the index is used.

This is what the generated BSO modified query looks like:
```sql
SELECT
  bso.userid,
  bso.collection,
  bso.id,
  bso.sortindex,
  bso.modified,
  bso.payload,
  bso.ttl
FROM
  bso
WHERE
  bso.userid = @userid
  AND bso.collection = @collectionid
  AND bso.modified > @newer
  AND bso.ttl > @ttl
ORDER BY
  bso.modified DESC,
  bso.id ASC
```

Since the query also runs with modified in DESC order, the index should also be updated to store modifed in DESC order to optimize the speed of that query.

**Comment by bbangert** [comment]
**Open question**: Should this index be interleaved?

In Spanner, secondary indexes are implemented as their own tables, which implies that the index will be sharded across the Spanner cluster as any other table is. When using a secondary index and forcing the join, Spanner will load the additional data by doing a join of the index table results with the BSO table, per:

> For example, in the definition of the AlbumsByAlbumTitle index above, the MarketingBudget column is not stored in the index, but is one of the selected columns in the SQL query on that index. To fetch this column, Cloud Spanner does a lookup of the MarketingBudget column from the base table under the hood and joins it with data from the index to return the query results. You can avoid this extra join by storing the MarketingBudget column in the index; see STORING clause below.

Interleaving the index *should, if I understand this correctly*, result in the desired index rows being present on the same node as the users BSO data and avoid Spanner node coordination for the table join. We could validate this by testing with and without interleaving the index, or ask a Google Spanner expert.

**Comment by pjenvey** [comment]
DESC is the default sort order but the client's also allowed to specify an ASC sort order. I don't know if our clients impl actually use it.

> Interleaving the index _should, if I understand this correctly_, result in the desired index rows being present on the same node as the users BSO data and avoid Spanner node coordination for the table join. We could validate this by testing with and without interleaving the index, or ask a Google Spanner expert.

Yup, I can see this is the case w/ the execution plan in the dashboard.

Both cases now using FORCE_INDEX=BsoLastModified,

Without interleaving we get a distributed cross apply:
<img width="1605" alt="Screen Shot 2019-03-13 at 5 09 05 PM" src="https://user-images.githubusercontent.com/14639/54549119-a24da480-4966-11e9-954a-91f4d1bd32c0.png">

w/ interleaving into user_collections we get a local cross apply:
<img width="992" alt="Screen Shot 2019-03-14 at 10 53 33 AM" src="https://user-images.githubusercontent.com/14639/54549256-eb055d80-4966-11e9-98f4-6e50c591db17.png">

Also our other index is for the purge script to intermittently delete old bsos by TTL:
`CREATE INDEX BsoTtl ON bso(ttl);`

There's no FORCE_INDEX directive to delete but according to its execution plan a simple DELETE statement by ttl does utilize it. It can't be interleaved (doesn't include: userid, collection)
