### ISSUE TITLE
Failing atomic/batch uploads tests

### ISSUE THREAD

**Issue by rtilder** [mozilla-services/server-syncstorage#39]
test_purgettl_script fails if memcached isn't running, at least with the sqlite backend.  Possibly only with the sqlite backend.

test_batch_ttl_update and test_batch_ttl_is_based_on_commit_timestamp are still being skipped.  Errors for test_batch_ttl_update seem to indicate that the commit query, at least for sqlite, may not be kosher.

**Comment by rfk** [comment]
> test_purgettl_script fails if memcached isn't running, at least with the sqlite backend. Possibly only with the sqlite backend.

@rtilder it seems to be passing for me now, can you confirm whether this is still an issue?

**Comment by rfk** [comment]
Now tracking in https://bugzilla.mozilla.org/show_bug.cgi?id=1311903, closing here
