### ISSUE TITLE
Load tests need update to molotov/loads-broker compatibility

### ISSUE THREAD

**Issue by karlht** [mozilla-services/server-syncstorage#57]
The load tests in the `loadtests` directory were originally written for Loads v1, which is no longer in use.

The two load testing frameworks currently in use in Firefox Test Engineering are https://github.com/loads/molotov and https://github.com/loads/loads-broker -- the load tests here need an upgrade to be compatible with either or both of these frameworks.

**Comment by tarekziade** [comment]
Started here - https://github.com/mozilla-services/syncstorage-loadtest

should be ready monday-ish

**Comment by tarekziade** [comment]
I have the first draft, but the Hawk auth process is broken in the original test, will work on this with @rfk

**Comment by rfk** [comment]
@tarekziade thanks for digging into these tests!  I think I found the auth issue you were hitting: https://github.com/mozilla-services/syncstorage-loadtest/pull/1

**Comment by tarekziade** [comment]
ah thanks a lot @rfk! since the original script did some 401 as well I assumed something else was wrong.

**Comment by tarekziade** [comment]
the test was ported to Molotov at https://github.com/mozilla-services/syncstorage-loadtest

**Comment by karlht** [comment]
Marvellous.  Thank you, Tarek!
