### ISSUE TITLE
Inconsistency between BATCH_MAX_BYTES and BATCH_MAX_COUNT

### ISSUE THREAD

**Issue by mhammond** [mozilla-services/server-syncstorage#73]
As @thomcc found in https://bugzilla.mozilla.org/show_bug.cgi?id=1393659, BATCH_MAX_COUNT is, as its name implies, an "inclusive" max - the count can be equal to the max. However, BATCH_MAX_BYTES is exclusive - if the number of bytes is equal to that value, the BSO will be rejected.

These should be consistent. IMO, BATCH_MAX_BYTES should be made inclusive.

https://github.com/mozilla-services/server-syncstorage/blob/master/syncstorage/views/validators.py#L306-L313

(Note that in that bug we are accounting for this behaviour, so this bug isn't blocking desktop. However, it's not clear other implementations take this into account, nor that future implementations will)

**Comment by rfk** [comment]
Agreed, thanks @mhammond!
