### ISSUE TITLE
Obsolete README note about the 1.5 version

### ISSUE THREAD

**Issue by flaki** [mozilla-services/server-syncstorage#80]
The README states:
> If you want to run a self-hosted version of the Sync Server for use with existing versions of Firefox, you should start from here:

However, the linked page notes:
> Note: These instructions are for the sync server protocol used by Firefox 28 and earlier. Firefox 29 and later include a new sync service that is incompatible with this server. For a server compatible with Firefox 29 and later, see Run your own Sync-1.5 Server.

Therefore, 1.5 is clearly already used in production and the README note is misleading and obsolete.

**Comment by rfk** [comment]
Thanks @flaki, that is indeed *extremely* out of date!  I've updated the text in https://github.com/mozilla-services/server-syncstorage/commit/149496f09b0ff8ba21cec1d107d2435cb1f584f7
